name: kandangapp
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  fluttertoast: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Samsung
      fonts:
        - asset: assets/fonts/samsung/SamsungSans-Bold.ttf
        - asset: assets/fonts/samsung/SamsungSans-Light.ttf
        - asset: assets/fonts/samsung/SamsungSans-Medium.ttf
        - asset: assets/fonts/samsung/SamsungSans-Regular.ttf
        - asset: assets/fonts/samsung/SamsungSans-Thin.ttf
