name: kandangapp
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  fluttertoast: ^3.1.3
  shared_preferences: ^0.5.3+4
  rxdart: ^0.22.6
  http: ^0.12.0+2
  font_awesome_flutter: ^8.5.0
  cached_network_image: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Samsung
      fonts:
        - asset: assets/fonts/samsung/SamsungSans-Bold.ttf
        - asset: assets/fonts/samsung/SamsungSans-Light.ttf
        - asset: assets/fonts/samsung/SamsungSans-Medium.ttf
        - asset: assets/fonts/samsung/SamsungSans-Regular.ttf
        - asset: assets/fonts/samsung/SamsungSans-Thin.ttf
